/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.moaclient.models


import com.squareup.moshi.Json

/**
 * 
 * @param accessToken 
 * @param userType 
 */

data class MoaAuthenticationOutput (
    @Json(name = "accessToken")
    val accessToken: kotlin.String? = null,
    @Json(name = "userType")
    val userType: MoaAuthenticationOutput.UserType? = null
) {

    /**
     * 
     * Values: aDMINISTRATOR,mERCHANT,cUSTOMER
     */
    enum class UserType(val value: kotlin.String) {
        @Json(name = "ADMINISTRATOR") aDMINISTRATOR("ADMINISTRATOR"),
        @Json(name = "MERCHANT") mERCHANT("MERCHANT"),
        @Json(name = "CUSTOMER") cUSTOMER("CUSTOMER");
    }
}

