/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.moaclient.models


import com.squareup.moshi.Json

/**
 * 
 * @param locationMoaId 
 */

data class MoaOrderCreateInput (
    @Json(name = "locationMoaId")
    val locationMoaId: kotlin.String
)

