/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.moaclient.models

import com.adeptry.moaclient.models.SquareAddress

import com.squareup.moshi.Json

/**
 * 
 * @param cardNonce 
 * @param billingAddress 
 * @param cardholderName 
 */

data class SquareCreateCustomerCardInput (
    @Json(name = "cardNonce")
    val cardNonce: kotlin.String,
    @Json(name = "billingAddress")
    val billingAddress: SquareAddress? = null,
    @Json(name = "cardholderName")
    val cardholderName: kotlin.String? = null
)

