/**
* MyOrderApp
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.myorderapp.client.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param ulidKey 
 * @param dateAndTime 
 * @param type 
 * @param name 
 * @param status 
 * @param uploadedDate 
 * @param percent 
 * @param size 
 * @param lastModifiedDate 
 * @param previewUrl 
 * @param duration 
 * @param width 
 * @param height 
 * @param videoWidth 
 * @param videoHeight 
 * @param thumbnailUrl 
 * @param detailUrl 
 * @param moaId 
 * @param createDate 
 * @param updateDate 
 * @param deleteDate 
 * @param version 
 */

data class MoaAWSS3File (
    @Json(name = "ulidKey")
    val ulidKey: kotlin.String? = null,
    @Json(name = "dateAndTime")
    val dateAndTime: org.threeten.bp.OffsetDateTime? = null,
    @Json(name = "type")
    val type: kotlin.String? = null,
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "status")
    val status: kotlin.String? = null,
    @Json(name = "uploadedDate")
    val uploadedDate: kotlin.String? = null,
    @Json(name = "percent")
    val percent: Double? = null,
    @Json(name = "size")
    val size: Double? = null,
    @Json(name = "lastModifiedDate")
    val lastModifiedDate: kotlin.String? = null,
    @Json(name = "previewUrl")
    val previewUrl: kotlin.String? = null,
    @Json(name = "duration")
    val duration: Double? = null,
    @Json(name = "width")
    val width: Double? = null,
    @Json(name = "height")
    val height: Double? = null,
    @Json(name = "videoWidth")
    val videoWidth: Double? = null,
    @Json(name = "videoHeight")
    val videoHeight: Double? = null,
    @Json(name = "thumbnailUrl")
    val thumbnailUrl: kotlin.String? = null,
    @Json(name = "detailUrl")
    val detailUrl: kotlin.String? = null,
    @Json(name = "moaId")
    val moaId: kotlin.String? = null,
    @Json(name = "createDate")
    val createDate: org.threeten.bp.OffsetDateTime? = null,
    @Json(name = "updateDate")
    val updateDate: org.threeten.bp.OffsetDateTime? = null,
    @Json(name = "deleteDate")
    val deleteDate: org.threeten.bp.OffsetDateTime? = null,
    @Json(name = "version")
    val version: Double? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

