/**
* MyOrderApp
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.myorderapp.client.models

import com.adeptry.myorderapp.client.models.MoaAlertDto
import com.adeptry.myorderapp.client.models.MoaOptionalUpdateDto

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param alert 
 * @param requiredUpdate 
 * @param optionalUpdate 
 */

data class MoaAppConfigurationDto (
    @Json(name = "alert")
    val alert: MoaAlertDto? = null,
    @Json(name = "requiredUpdate")
    val requiredUpdate: kotlin.Any? = null,
    @Json(name = "optionalUpdate")
    val optionalUpdate: MoaOptionalUpdateDto? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

