/**
* MyOrderApp
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.myorderapp.client.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param accessToken 
 * @param userType 
 */

data class MoaAuthenticationOutput (
    @Json(name = "accessToken")
    val accessToken: kotlin.String? = null,
    @Json(name = "userType")
    val userType: MoaAuthenticationOutput.UserType? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

    /**
     * 
     * Values: ADMINISTRATOR,MERCHANT,CUSTOMER
     */
    enum class UserType(val value: kotlin.String) {
        @Json(name = "ADMINISTRATOR") ADMINISTRATOR("ADMINISTRATOR"),
        @Json(name = "MERCHANT") MERCHANT("MERCHANT"),
        @Json(name = "CUSTOMER") CUSTOMER("CUSTOMER");
    }
}

