/**
* MyOrderApp
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.myorderapp.client.models

import com.adeptry.myorderapp.client.models.MoaAppConfigurationDto

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param ios 
 * @param android 
 */

data class MoaConfigurationDto (
    @Json(name = "ios")
    val ios: MoaAppConfigurationDto? = null,
    @Json(name = "android")
    val android: MoaAppConfigurationDto? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

