/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.myorderapp.client.models

import com.adeptry.myorderapp.client.models.MoaMerchant
import com.adeptry.myorderapp.client.models.MoaOrder

import com.squareup.moshi.Json

/**
 * 
 * @param accessToken 
 * @param currentOrder 
 * @param orders 
 * @param moaId 
 * @param createDate 
 * @param updateDate 
 * @param email 
 * @param phoneNumber 
 * @param merchantMoaId 
 * @param merchant 
 */

data class MoaCustomer (
    @Json(name = "accessToken")
    val accessToken: kotlin.String? = null,
    @Json(name = "currentOrder")
    val currentOrder: MoaOrder? = null,
    @Json(name = "orders")
    val orders: kotlin.collections.List<MoaOrder>? = null,
    @Json(name = "moaId")
    val moaId: kotlin.String? = null,
    @Json(name = "createDate")
    val createDate: org.threeten.bp.OffsetDateTime? = null,
    @Json(name = "updateDate")
    val updateDate: org.threeten.bp.OffsetDateTime? = null,
    @Json(name = "email")
    val email: kotlin.String? = null,
    @Json(name = "phoneNumber")
    val phoneNumber: kotlin.String? = null,
    @Json(name = "merchantMoaId")
    val merchantMoaId: kotlin.String? = null,
    @Json(name = "merchant")
    val merchant: MoaMerchant? = null
)

