/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.myorderapp.client.models

import com.adeptry.myorderapp.client.models.MoaCatalog
import com.adeptry.myorderapp.client.models.MoaItem

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize


/**
 * 
 * @param catalog 
 * @param items 
 * @param moaId 
 * @param createDate 
 * @param updateDate 
 * @param squareId 
 * @param name 
 */
@Parcelize

data class MoaCategory (
    @Json(name = "catalog")
    val catalog: MoaCatalog? = null,
    @Json(name = "items")
    val items: kotlin.collections.List<MoaItem>? = null,
    @Json(name = "moaId")
    val moaId: kotlin.String? = null,
    @Json(name = "createDate")
    val createDate: java.time.OffsetDateTime? = null,
    @Json(name = "updateDate")
    val updateDate: java.time.OffsetDateTime? = null,
    @Json(name = "squareId")
    val squareId: kotlin.String? = null,
    @Json(name = "name")
    val name: kotlin.String? = null
) : Parcelable

