/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.myorderapp.client.models

import com.adeptry.myorderapp.client.models.MoaCategory
import com.adeptry.myorderapp.client.models.MoaMerchant

import com.squareup.moshi.Json

/**
 * 
 * @param categories 
 * @param merchant 
 * @param moaId 
 * @param createDate 
 * @param updateDate 
 */

data class MoaCatalog (
    @Json(name = "categories")
    val categories: kotlin.collections.List<MoaCategory>? = null,
    @Json(name = "merchant")
    val merchant: MoaMerchant? = null,
    @Json(name = "moaId")
    val moaId: kotlin.String? = null,
    @Json(name = "createDate")
    val createDate: org.threeten.bp.OffsetDateTime? = null,
    @Json(name = "updateDate")
    val updateDate: org.threeten.bp.OffsetDateTime? = null
)

