/**
* MyOrderApp
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.myorderapp.client.models

import com.adeptry.myorderapp.client.models.MoaMerchant

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param merchant 
 * @param alertMessage 
 * @param alertBlocking 
 * @param optionalVersionIOS 
 * @param optionalVersionMessageIOS 
 * @param optionalVersionAndroid 
 * @param optionalVersionMessageAndroid 
 * @param minimumVersionIOS 
 * @param minimumVersionMessageIOS 
 * @param minimumVersionAndroid 
 * @param minimumVersionMessageAndroid 
 * @param moaId 
 * @param createDate 
 * @param updateDate 
 * @param deleteDate 
 * @param version 
 */

data class MoaConfiguration (
    @Json(name = "merchant")
    val merchant: MoaMerchant? = null,
    @Json(name = "alertMessage")
    val alertMessage: kotlin.String? = null,
    @Json(name = "alertBlocking")
    val alertBlocking: kotlin.Boolean? = null,
    @Json(name = "optionalVersion_iOS")
    val optionalVersionIOS: kotlin.String? = null,
    @Json(name = "optionalVersionMessage_iOS")
    val optionalVersionMessageIOS: kotlin.String? = null,
    @Json(name = "optionalVersionAndroid")
    val optionalVersionAndroid: kotlin.String? = null,
    @Json(name = "optionalVersionMessageAndroid")
    val optionalVersionMessageAndroid: kotlin.String? = null,
    @Json(name = "minimumVersion_iOS")
    val minimumVersionIOS: kotlin.String? = null,
    @Json(name = "minimumVersionMessage_iOS")
    val minimumVersionMessageIOS: kotlin.String? = null,
    @Json(name = "minimumVersionAndroid")
    val minimumVersionAndroid: kotlin.String? = null,
    @Json(name = "minimumVersionMessageAndroid")
    val minimumVersionMessageAndroid: kotlin.String? = null,
    @Json(name = "moaId")
    val moaId: kotlin.String? = null,
    @Json(name = "createDate")
    val createDate: org.threeten.bp.OffsetDateTime? = null,
    @Json(name = "updateDate")
    val updateDate: org.threeten.bp.OffsetDateTime? = null,
    @Json(name = "deleteDate")
    val deleteDate: org.threeten.bp.OffsetDateTime? = null,
    @Json(name = "version")
    val version: Double? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

