/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.myorderapp.client.models

import com.adeptry.myorderapp.client.models.MoaCategory
import com.adeptry.myorderapp.client.models.MoaModifierList
import com.adeptry.myorderapp.client.models.MoaVariation

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize


/**
 * 
 * @param category 
 * @param modifierLists 
 * @param variations 
 * @param moaId 
 * @param createDate 
 * @param updateDate 
 * @param squareId 
 * @param name 
 * @param priceInCents 
 * @param description 
 * @param categoryMoaId 
 */
@Parcelize

data class MoaItem (
    @Json(name = "category")
    val category: MoaCategory? = null,
    @Json(name = "modifierLists")
    val modifierLists: kotlin.collections.List<MoaModifierList>? = null,
    @Json(name = "variations")
    val variations: kotlin.collections.List<MoaVariation>? = null,
    @Json(name = "moaId")
    val moaId: kotlin.String? = null,
    @Json(name = "createDate")
    val createDate: java.time.OffsetDateTime? = null,
    @Json(name = "updateDate")
    val updateDate: java.time.OffsetDateTime? = null,
    @Json(name = "squareId")
    val squareId: kotlin.String? = null,
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "priceInCents")
    val priceInCents: java.math.BigDecimal? = null,
    @Json(name = "description")
    val description: kotlin.String? = null,
    @Json(name = "categoryMoaId")
    val categoryMoaId: kotlin.String? = null
) : Parcelable

