/**
* MyOrderApp
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.myorderapp.client.models

import com.adeptry.myorderapp.client.models.MoaAWSS3File
import com.adeptry.myorderapp.client.models.MoaCatalog
import com.adeptry.myorderapp.client.models.MoaConfiguration

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param logo 
 * @param catalog 
 * @param configuration 
 * @param email 
 * @param fullName 
 * @param phoneNumber 
 * @param primaryColor 
 * @param secondaryColor 
 * @param fontFamily 
 * @param catalogMoaId 
 * @param configurationMoaId 
 * @param moaId 
 * @param createDate 
 * @param updateDate 
 * @param deleteDate 
 * @param version 
 */

data class MoaMerchant (
    @Json(name = "logo")
    val logo: MoaAWSS3File? = null,
    @Json(name = "catalog")
    val catalog: MoaCatalog? = null,
    @Json(name = "configuration")
    val configuration: MoaConfiguration? = null,
    @Json(name = "email")
    val email: kotlin.String? = null,
    @Json(name = "fullName")
    val fullName: kotlin.String? = null,
    @Json(name = "phoneNumber")
    val phoneNumber: kotlin.String? = null,
    @Json(name = "primaryColor")
    val primaryColor: kotlin.String? = null,
    @Json(name = "secondaryColor")
    val secondaryColor: kotlin.String? = null,
    @Json(name = "fontFamily")
    val fontFamily: kotlin.String? = null,
    @Json(name = "catalogMoaId")
    val catalogMoaId: kotlin.String? = null,
    @Json(name = "configurationMoaId")
    val configurationMoaId: kotlin.String? = null,
    @Json(name = "moaId")
    val moaId: kotlin.String? = null,
    @Json(name = "createDate")
    val createDate: org.threeten.bp.OffsetDateTime? = null,
    @Json(name = "updateDate")
    val updateDate: org.threeten.bp.OffsetDateTime? = null,
    @Json(name = "deleteDate")
    val deleteDate: org.threeten.bp.OffsetDateTime? = null,
    @Json(name = "version")
    val version: Double? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

