/**
* MyOrderApp
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.myorderapp.client.models

import com.adeptry.myorderapp.client.models.MoaCustomer
import com.adeptry.myorderapp.client.models.MoaLocation
import com.adeptry.myorderapp.client.models.MoaMerchant
import com.adeptry.myorderapp.client.models.SquareOrder
import com.adeptry.myorderapp.client.models.SquarePayment

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param squareOrder 
 * @param squarePayment 
 * @param customer 
 * @param orderSquareId 
 * @param paymentSquareId 
 * @param customerMoaId 
 * @param merchantMoaId 
 * @param merchant 
 * @param locationMoaId 
 * @param location 
 * @param moaId 
 * @param createDate 
 * @param updateDate 
 * @param deleteDate 
 * @param version 
 */

data class MoaOrder (
    @Json(name = "squareOrder")
    val squareOrder: SquareOrder? = null,
    @Json(name = "squarePayment")
    val squarePayment: SquarePayment? = null,
    @Json(name = "customer")
    val customer: MoaCustomer? = null,
    @Json(name = "orderSquareId")
    val orderSquareId: kotlin.String? = null,
    @Json(name = "paymentSquareId")
    val paymentSquareId: kotlin.String? = null,
    @Json(name = "customerMoaId")
    val customerMoaId: kotlin.String? = null,
    @Json(name = "merchantMoaId")
    val merchantMoaId: kotlin.String? = null,
    @Json(name = "merchant")
    val merchant: MoaMerchant? = null,
    @Json(name = "locationMoaId")
    val locationMoaId: kotlin.String? = null,
    @Json(name = "location")
    val location: MoaLocation? = null,
    @Json(name = "moaId")
    val moaId: kotlin.String? = null,
    @Json(name = "createDate")
    val createDate: org.threeten.bp.OffsetDateTime? = null,
    @Json(name = "updateDate")
    val updateDate: org.threeten.bp.OffsetDateTime? = null,
    @Json(name = "deleteDate")
    val deleteDate: org.threeten.bp.OffsetDateTime? = null,
    @Json(name = "version")
    val version: Double? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

