/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.myorderapp.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param variationMoaId 
 * @param quantity 
 * @param idempotencyKey 
 * @param modifiersMoaIds 
 */

data class MoaOrderAddInput (
    @Json(name = "variationMoaId")
    val variationMoaId: kotlin.String,
    @Json(name = "quantity")
    val quantity: java.math.BigDecimal,
    @Json(name = "idempotencyKey")
    val idempotencyKey: kotlin.String,
    @Json(name = "modifiersMoaIds")
    val modifiersMoaIds: kotlin.collections.List<kotlin.String>? = null
)

