/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.myorderapp.client.models


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize


/**
 * 
 * @param paymentSquareId 
 * @param idempotencyKey 
 */
@Parcelize

data class MoaOrderPayInput (
    @Json(name = "paymentSquareId")
    val paymentSquareId: kotlin.String,
    @Json(name = "idempotencyKey")
    val idempotencyKey: kotlin.String
) : Parcelable

