/**
* MyOrderApp
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.myorderapp.client.models

import com.adeptry.myorderapp.client.models.SquareAddress

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param cardNonce 
 * @param billingAddress 
 * @param cardholderName 
 */

data class SquareCreateCustomerCardInput (
    @Json(name = "cardNonce")
    val cardNonce: kotlin.String,
    @Json(name = "billingAddress")
    val billingAddress: SquareAddress? = null,
    @Json(name = "cardholderName")
    val cardholderName: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

