/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.myorderapp.client.models

import com.adeptry.myorderapp.client.models.SquareAddress

import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param expMonth 
 * @param expYear 
 * @param cardBrand 
 * @param last4 
 * @param cardholderName 
 * @param billingAddress 
 * @param fingerprint 
 * @param cardType 
 * @param prepaidType 
 * @param bin 
 */

data class SquareCard (
    @Json(name = "id")
    val id: kotlin.String? = null,
    @Json(name = "expMonth")
    val expMonth: Double? = null,
    @Json(name = "expYear")
    val expYear: Double? = null,
    @Json(name = "cardBrand")
    val cardBrand: kotlin.String? = null,
    @Json(name = "last4")
    val last4: kotlin.String? = null,
    @Json(name = "cardholderName")
    val cardholderName: kotlin.String? = null,
    @Json(name = "billingAddress")
    val billingAddress: SquareAddress? = null,
    @Json(name = "fingerprint")
    val fingerprint: kotlin.String? = null,
    @Json(name = "cardType")
    val cardType: kotlin.String? = null,
    @Json(name = "prepaidType")
    val prepaidType: kotlin.String? = null,
    @Json(name = "bin")
    val bin: kotlin.String? = null
)

