/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.myorderapp.client.models

import com.adeptry.myorderapp.client.models.SquareMoney

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize


/**
 * 
 * @param uid 
 * @param catalogObjectId 
 * @param name 
 * @param basePriceMoney 
 * @param totalPriceMoney 
 */
@Parcelize

data class SquareOrderLineItemModifier (
    @Json(name = "uid")
    val uid: kotlin.String? = null,
    @Json(name = "catalogObjectId")
    val catalogObjectId: kotlin.String? = null,
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "basePriceMoney")
    val basePriceMoney: SquareMoney? = null,
    @Json(name = "totalPriceMoney")
    val totalPriceMoney: SquareMoney? = null
) : Parcelable

