/**
* MyOrderApp
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.myorderapp.client.models

import com.adeptry.myorderapp.client.models.SquareMoney

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param id 
 * @param locationId 
 * @param transactionId 
 * @param createdAt 
 * @param note 
 * @param amountMoney 
 * @param tipMoney 
 * @param processingFeeMoney 
 * @param customerId 
 * @param type 
 * @param paymentId 
 */

data class SquareTender (
    @Json(name = "id")
    val id: kotlin.String? = null,
    @Json(name = "locationId")
    val locationId: kotlin.String? = null,
    @Json(name = "transactionId")
    val transactionId: kotlin.String? = null,
    @Json(name = "createdAt")
    val createdAt: kotlin.String? = null,
    @Json(name = "note")
    val note: kotlin.String? = null,
    @Json(name = "amountMoney")
    val amountMoney: SquareMoney? = null,
    @Json(name = "tipMoney")
    val tipMoney: SquareMoney? = null,
    @Json(name = "processingFeeMoney")
    val processingFeeMoney: SquareMoney? = null,
    @Json(name = "customerId")
    val customerId: kotlin.String? = null,
    @Json(name = "type")
    val type: kotlin.String? = null,
    @Json(name = "paymentId")
    val paymentId: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

