/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.myorderapp.client.models

import com.adeptry.myorderapp.client.models.SquareMoney

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize


/**
 * 
 * @param id 
 * @param locationId 
 * @param transactionId 
 * @param tenderId 
 * @param createdAt 
 * @param reason 
 * @param amountMoney 
 * @param status 
 * @param processingFeeMoney 
 */
@Parcelize

data class SquareRefund (
    @Json(name = "id")
    val id: kotlin.String? = null,
    @Json(name = "locationId")
    val locationId: kotlin.String? = null,
    @Json(name = "transactionId")
    val transactionId: kotlin.String? = null,
    @Json(name = "tenderId")
    val tenderId: kotlin.String? = null,
    @Json(name = "createdAt")
    val createdAt: kotlin.String? = null,
    @Json(name = "reason")
    val reason: kotlin.String? = null,
    @Json(name = "amountMoney")
    val amountMoney: SquareMoney? = null,
    @Json(name = "status")
    val status: kotlin.String? = null,
    @Json(name = "processingFeeMoney")
    val processingFeeMoney: SquareMoney? = null
) : Parcelable

