/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.moaclient.apis

import com.adeptry.moaclient.models.MoaAuthenticationInput
import com.adeptry.moaclient.models.MoaAuthenticationOutput

import com.adeptry.moaclient.infrastructure.ApiClient
import com.adeptry.moaclient.infrastructure.ClientException
import com.adeptry.moaclient.infrastructure.ClientError
import com.adeptry.moaclient.infrastructure.ServerException
import com.adeptry.moaclient.infrastructure.ServerError
import com.adeptry.moaclient.infrastructure.MultiValueMap
import com.adeptry.moaclient.infrastructure.RequestConfig
import com.adeptry.moaclient.infrastructure.RequestMethod
import com.adeptry.moaclient.infrastructure.ResponseType
import com.adeptry.moaclient.infrastructure.Success
import com.adeptry.moaclient.infrastructure.toMultiValue

class AuthenticationApi(basePath: kotlin.String = defaultBasePath) : ApiClient(basePath) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty("com.adeptry.moaclient.baseUrl", "http://localhost")
        }
    }

    /**
    * 
    * 
    * @param moaAuthenticationInput  
    * @return MoaAuthenticationOutput
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun authenticate(moaAuthenticationInput: MoaAuthenticationInput) : MoaAuthenticationOutput {
        val localVariableConfig = authenticateRequestConfig(moaAuthenticationInput = moaAuthenticationInput)

        val localVarResponse = request<MoaAuthenticationOutput>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MoaAuthenticationOutput
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation authenticate
    *
    * @param moaAuthenticationInput  
    * @return RequestConfig
    */
    fun authenticateRequestConfig(moaAuthenticationInput: MoaAuthenticationInput) : RequestConfig {
        val localVariableBody: kotlin.Any? = moaAuthenticationInput
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val localVariableConfig = RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/authentication",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )

        return localVariableConfig
    }

}
