/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.moaclient.apis

import com.adeptry.moaclient.models.MoaError
import com.adeptry.moaclient.models.SquareCard
import com.adeptry.moaclient.models.SquareCreateCustomerCardInput
import com.adeptry.moaclient.models.SquareDeleteCustomerCardInput

import com.adeptry.moaclient.infrastructure.ApiClient
import com.adeptry.moaclient.infrastructure.ClientException
import com.adeptry.moaclient.infrastructure.ClientError
import com.adeptry.moaclient.infrastructure.ServerException
import com.adeptry.moaclient.infrastructure.ServerError
import com.adeptry.moaclient.infrastructure.MultiValueMap
import com.adeptry.moaclient.infrastructure.RequestConfig
import com.adeptry.moaclient.infrastructure.RequestMethod
import com.adeptry.moaclient.infrastructure.ResponseType
import com.adeptry.moaclient.infrastructure.Success
import com.adeptry.moaclient.infrastructure.toMultiValue

class CardsApi(basePath: kotlin.String = defaultBasePath) : ApiClient(basePath) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty("com.adeptry.moaclient.baseUrl", "http://localhost")
        }
    }

    /**
    * 
    * 
    * @param squareCreateCustomerCardInput  
    * @return kotlin.collections.List<SquareCard>
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createCardForCurrentCustomer(squareCreateCustomerCardInput: SquareCreateCustomerCardInput) : kotlin.collections.List<SquareCard> {
        val localVariableConfig = createCardForCurrentCustomerRequestConfig(squareCreateCustomerCardInput = squareCreateCustomerCardInput)

        val localVarResponse = request<kotlin.collections.List<SquareCard>>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SquareCard>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation createCardForCurrentCustomer
    *
    * @param squareCreateCustomerCardInput  
    * @return RequestConfig
    */
    fun createCardForCurrentCustomerRequestConfig(squareCreateCustomerCardInput: SquareCreateCustomerCardInput) : RequestConfig {
        val localVariableBody: kotlin.Any? = squareCreateCustomerCardInput
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val localVariableConfig = RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/customers/current/cards",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )

        return localVariableConfig
    }

    /**
    * 
    * 
    * @param squareDeleteCustomerCardInput  
    * @return kotlin.collections.List<SquareCard>
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteCardForCurrentCustomer(squareDeleteCustomerCardInput: SquareDeleteCustomerCardInput) : kotlin.collections.List<SquareCard> {
        val localVariableConfig = deleteCardForCurrentCustomerRequestConfig(squareDeleteCustomerCardInput = squareDeleteCustomerCardInput)

        val localVarResponse = request<kotlin.collections.List<SquareCard>>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SquareCard>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation deleteCardForCurrentCustomer
    *
    * @param squareDeleteCustomerCardInput  
    * @return RequestConfig
    */
    fun deleteCardForCurrentCustomerRequestConfig(squareDeleteCustomerCardInput: SquareDeleteCustomerCardInput) : RequestConfig {
        val localVariableBody: kotlin.Any? = squareDeleteCustomerCardInput
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val localVariableConfig = RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/customers/current/cards",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )

        return localVariableConfig
    }

    /**
    * 
    * 
    * @return kotlin.collections.List<SquareCard>
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getCardsForCurrentCustomer() : kotlin.collections.List<SquareCard> {
        val localVariableConfig = getCardsForCurrentCustomerRequestConfig()

        val localVarResponse = request<kotlin.collections.List<SquareCard>>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<SquareCard>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation getCardsForCurrentCustomer
    *
    * @return RequestConfig
    */
    fun getCardsForCurrentCustomerRequestConfig() : RequestConfig {
        val localVariableBody: kotlin.Any? = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val localVariableConfig = RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/customers/current/cards",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )

        return localVariableConfig
    }

}
