/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.moaclient.apis

import com.adeptry.moaclient.models.MoaCustomer
import com.adeptry.moaclient.models.MoaCustomerCreateInput
import com.adeptry.moaclient.models.MoaCustomerUpdateInput
import com.adeptry.moaclient.models.MoaError

import com.adeptry.moaclient.infrastructure.ApiClient
import com.adeptry.moaclient.infrastructure.ClientException
import com.adeptry.moaclient.infrastructure.ClientError
import com.adeptry.moaclient.infrastructure.ServerException
import com.adeptry.moaclient.infrastructure.ServerError
import com.adeptry.moaclient.infrastructure.MultiValueMap
import com.adeptry.moaclient.infrastructure.RequestConfig
import com.adeptry.moaclient.infrastructure.RequestMethod
import com.adeptry.moaclient.infrastructure.ResponseType
import com.adeptry.moaclient.infrastructure.Success
import com.adeptry.moaclient.infrastructure.toMultiValue

class CustomersApi(basePath: kotlin.String = defaultBasePath) : ApiClient(basePath) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty("com.adeptry.moaclient.baseUrl", "http://localhost")
        }
    }

    /**
    * 
    * 
    * @param moaCustomerCreateInput  
    * @return MoaCustomer
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createCustomer(moaCustomerCreateInput: MoaCustomerCreateInput) : MoaCustomer {
        val localVariableConfig = createCustomerRequestConfig(moaCustomerCreateInput = moaCustomerCreateInput)

        val localVarResponse = request<MoaCustomer>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MoaCustomer
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation createCustomer
    *
    * @param moaCustomerCreateInput  
    * @return RequestConfig
    */
    fun createCustomerRequestConfig(moaCustomerCreateInput: MoaCustomerCreateInput) : RequestConfig {
        val localVariableBody: kotlin.Any? = moaCustomerCreateInput
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val localVariableConfig = RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/customers",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )

        return localVariableConfig
    }

    /**
    * 
    * 
    * @return MoaCustomer
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getCurrentCustomer() : MoaCustomer {
        val localVariableConfig = getCurrentCustomerRequestConfig()

        val localVarResponse = request<MoaCustomer>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MoaCustomer
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation getCurrentCustomer
    *
    * @return RequestConfig
    */
    fun getCurrentCustomerRequestConfig() : RequestConfig {
        val localVariableBody: kotlin.Any? = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val localVariableConfig = RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/customers/current",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )

        return localVariableConfig
    }

    /**
    * 
    * 
    * @param moaCustomerUpdateInput  
    * @return MoaCustomer
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateCurrentCustomer(moaCustomerUpdateInput: MoaCustomerUpdateInput) : MoaCustomer {
        val localVariableConfig = updateCurrentCustomerRequestConfig(moaCustomerUpdateInput = moaCustomerUpdateInput)

        val localVarResponse = request<MoaCustomer>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MoaCustomer
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation updateCurrentCustomer
    *
    * @param moaCustomerUpdateInput  
    * @return RequestConfig
    */
    fun updateCurrentCustomerRequestConfig(moaCustomerUpdateInput: MoaCustomerUpdateInput) : RequestConfig {
        val localVariableBody: kotlin.Any? = moaCustomerUpdateInput
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val localVariableConfig = RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/customers/current",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )

        return localVariableConfig
    }

}
