/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.adeptry.moaclient.apis

import com.adeptry.moaclient.models.MoaError
import com.adeptry.moaclient.models.MoaLocation

import com.adeptry.moaclient.infrastructure.ApiClient
import com.adeptry.moaclient.infrastructure.ClientException
import com.adeptry.moaclient.infrastructure.ClientError
import com.adeptry.moaclient.infrastructure.ServerException
import com.adeptry.moaclient.infrastructure.ServerError
import com.adeptry.moaclient.infrastructure.MultiValueMap
import com.adeptry.moaclient.infrastructure.RequestConfig
import com.adeptry.moaclient.infrastructure.RequestMethod
import com.adeptry.moaclient.infrastructure.ResponseType
import com.adeptry.moaclient.infrastructure.Success
import com.adeptry.moaclient.infrastructure.toMultiValue

class LocationsApi(basePath: kotlin.String = defaultBasePath) : ApiClient(basePath) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty("com.adeptry.moaclient.baseUrl", "http://localhost")
        }
    }

    /**
    * 
    * 
    * @return kotlin.collections.List<MoaLocation>
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getCurrentCustomersMerchantsLocations() : kotlin.collections.List<MoaLocation> {
        val localVariableConfig = getCurrentCustomersMerchantsLocationsRequestConfig()

        val localVarResponse = request<kotlin.collections.List<MoaLocation>>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<MoaLocation>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation getCurrentCustomersMerchantsLocations
    *
    * @return RequestConfig
    */
    fun getCurrentCustomersMerchantsLocationsRequestConfig() : RequestConfig {
        val localVariableBody: kotlin.Any? = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val localVariableConfig = RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/customers/current/merchant/locations",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )

        return localVariableConfig
    }

    /**
    * 
    * 
    * @param moaId  
    * @return kotlin.collections.List<MoaLocation>
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getMerchantLocations(moaId: kotlin.String) : kotlin.collections.List<MoaLocation> {
        val localVariableConfig = getMerchantLocationsRequestConfig(moaId = moaId)

        val localVarResponse = request<kotlin.collections.List<MoaLocation>>(
            localVariableConfig
        )

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<MoaLocation>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * To obtain the request config of the operation getMerchantLocations
    *
    * @param moaId  
    * @return RequestConfig
    */
    fun getMerchantLocationsRequestConfig(moaId: kotlin.String) : RequestConfig {
        val localVariableBody: kotlin.Any? = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        val localVariableConfig = RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/merchants/{moaId}/locations".replace("{"+"moaId"+"}", "$moaId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )

        return localVariableConfig
    }

}
