/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.myorderapp.kotlin-client.models

import org.myorderapp.kotlin-client.models.MoaCategory
import org.myorderapp.kotlin-client.models.MoaMerchant

import com.squareup.moshi.Json

/**
 * 
 * @param categories 
 * @param merchant 
 * @param id 
 * @param createDate 
 * @param updateDate 
 */

data class MoaCatalog (
    @Json(name = "categories")
    val categories: kotlin.collections.List<MoaCategory>? = null,
    @Json(name = "merchant")
    val merchant: MoaMerchant? = null,
    @Json(name = "id")
    val id: kotlin.String? = null,
    @Json(name = "createDate")
    val createDate: java.time.OffsetDateTime? = null,
    @Json(name = "updateDate")
    val updateDate: java.time.OffsetDateTime? = null
)

