/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.myorderapp.kotlin-client.models

import org.myorderapp.kotlin-client.models.MoaCustomer
import org.myorderapp.kotlin-client.models.MoaLocation
import org.myorderapp.kotlin-client.models.MoaMerchant
import org.myorderapp.kotlin-client.models.SquareOrder
import org.myorderapp.kotlin-client.models.SquarePayment

import com.squareup.moshi.Json

/**
 * 
 * @param squareOrder 
 * @param squarePayment 
 * @param customer 
 * @param id 
 * @param createDate 
 * @param updateDate 
 * @param squareOrderId 
 * @param squarePaymentId 
 * @param customerId 
 * @param merchantId 
 * @param merchant 
 * @param locationId 
 * @param location 
 */

data class MoaOrder (
    @Json(name = "squareOrder")
    val squareOrder: SquareOrder? = null,
    @Json(name = "squarePayment")
    val squarePayment: SquarePayment? = null,
    @Json(name = "customer")
    val customer: MoaCustomer? = null,
    @Json(name = "id")
    val id: kotlin.String? = null,
    @Json(name = "createDate")
    val createDate: java.time.OffsetDateTime? = null,
    @Json(name = "updateDate")
    val updateDate: java.time.OffsetDateTime? = null,
    @Json(name = "squareOrderId")
    val squareOrderId: kotlin.String? = null,
    @Json(name = "squarePaymentId")
    val squarePaymentId: kotlin.String? = null,
    @Json(name = "customerId")
    val customerId: kotlin.String? = null,
    @Json(name = "merchantId")
    val merchantId: kotlin.String? = null,
    @Json(name = "merchant")
    val merchant: MoaMerchant? = null,
    @Json(name = "locationId")
    val locationId: kotlin.String? = null,
    @Json(name = "location")
    val location: MoaLocation? = null
)

