/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.myorderapp.kotlin-client.models


import com.squareup.moshi.Json

/**
 * 
 * @param variationId 
 * @param quantity 
 * @param idempotencyKey 
 * @param modifiersIds 
 */

data class MoaOrderAddInput (
    @Json(name = "variationId")
    val variationId: kotlin.String,
    @Json(name = "quantity")
    val quantity: java.math.BigDecimal,
    @Json(name = "idempotencyKey")
    val idempotencyKey: kotlin.String,
    @Json(name = "modifiersIds")
    val modifiersIds: kotlin.collections.List<kotlin.String>? = null
)

