/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.myorderapp.kotlin-client.models

import org.myorderapp.kotlin-client.models.MoaCustomer
import org.myorderapp.kotlin-client.models.MoaLocation
import org.myorderapp.kotlin-client.models.MoaMerchant
import org.myorderapp.kotlin-client.models.SquareOrder
import org.myorderapp.kotlin-client.models.SquarePayment

import com.squareup.moshi.Json

/**
 * 
 * @param squareOrder 
 * @param squarePayment 
 * @param customer 
 * @param moaId 
 * @param createDate 
 * @param updateDate 
 * @param orderSquareId 
 * @param paymentSquareId 
 * @param customerMoaId 
 * @param merchantMoaId 
 * @param merchant 
 * @param locationMoaId 
 * @param location 
 */

data class MoaOrder (
    @Json(name = "squareOrder")
    val squareOrder: SquareOrder? = null,
    @Json(name = "squarePayment")
    val squarePayment: SquarePayment? = null,
    @Json(name = "customer")
    val customer: MoaCustomer? = null,
    @Json(name = "moaId")
    val moaId: kotlin.String? = null,
    @Json(name = "createDate")
    val createDate: java.time.OffsetDateTime? = null,
    @Json(name = "updateDate")
    val updateDate: java.time.OffsetDateTime? = null,
    @Json(name = "orderSquareId")
    val orderSquareId: kotlin.String? = null,
    @Json(name = "paymentSquareId")
    val paymentSquareId: kotlin.String? = null,
    @Json(name = "customerMoaId")
    val customerMoaId: kotlin.String? = null,
    @Json(name = "merchantMoaId")
    val merchantMoaId: kotlin.String? = null,
    @Json(name = "merchant")
    val merchant: MoaMerchant? = null,
    @Json(name = "locationMoaId")
    val locationMoaId: kotlin.String? = null,
    @Json(name = "location")
    val location: MoaLocation? = null
)

