/**
* MyOrderApp
* API for MyOrderApp
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.myorderapp.kotlin-client.models

import org.myorderapp.kotlin-client.models.SquareMoney
import org.myorderapp.kotlin-client.models.SquareOrderFulfillment
import org.myorderapp.kotlin-client.models.SquareOrderLineItem
import org.myorderapp.kotlin-client.models.SquareOrderLineItemDiscount
import org.myorderapp.kotlin-client.models.SquareOrderLineItemTax
import org.myorderapp.kotlin-client.models.SquareOrderMoneyAmounts
import org.myorderapp.kotlin-client.models.SquareOrderRoundingAdjustment
import org.myorderapp.kotlin-client.models.SquareOrderServiceCharge
import org.myorderapp.kotlin-client.models.SquareRefund
import org.myorderapp.kotlin-client.models.SquareTender

import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param locationId 
 * @param referenceId 
 * @param customerId 
 * @param lineItems 
 * @param taxes 
 * @param discounts 
 * @param serviceCharges 
 * @param fulfillments 
 * @param returnAmounts 
 * @param netAmounts 
 * @param roundingAdjustment 
 * @param tenders 
 * @param refunds 
 * @param createdAt 
 * @param updatedAt 
 * @param closedAt 
 * @param state 
 * @param version 
 * @param totalMoney 
 * @param totalTaxMoney 
 * @param totalDiscountMoney 
 * @param totalTipMoney 
 * @param totalServiceChargeMoney 
 */

data class SquareOrder (
    @Json(name = "id")
    val id: kotlin.String? = null,
    @Json(name = "locationId")
    val locationId: kotlin.String? = null,
    @Json(name = "referenceId")
    val referenceId: kotlin.String? = null,
    @Json(name = "customerId")
    val customerId: kotlin.String? = null,
    @Json(name = "lineItems")
    val lineItems: kotlin.collections.List<SquareOrderLineItem>? = null,
    @Json(name = "taxes")
    val taxes: kotlin.collections.List<SquareOrderLineItemTax>? = null,
    @Json(name = "discounts")
    val discounts: kotlin.collections.List<SquareOrderLineItemDiscount>? = null,
    @Json(name = "serviceCharges")
    val serviceCharges: kotlin.collections.List<SquareOrderServiceCharge>? = null,
    @Json(name = "fulfillments")
    val fulfillments: kotlin.collections.List<SquareOrderFulfillment>? = null,
    @Json(name = "returnAmounts")
    val returnAmounts: SquareOrderMoneyAmounts? = null,
    @Json(name = "netAmounts")
    val netAmounts: SquareOrderMoneyAmounts? = null,
    @Json(name = "roundingAdjustment")
    val roundingAdjustment: SquareOrderRoundingAdjustment? = null,
    @Json(name = "tenders")
    val tenders: kotlin.collections.List<SquareTender>? = null,
    @Json(name = "refunds")
    val refunds: kotlin.collections.List<SquareRefund>? = null,
    @Json(name = "createdAt")
    val createdAt: kotlin.String? = null,
    @Json(name = "updatedAt")
    val updatedAt: kotlin.String? = null,
    @Json(name = "closedAt")
    val closedAt: kotlin.String? = null,
    @Json(name = "state")
    val state: kotlin.String? = null,
    @Json(name = "version")
    val version: java.math.BigDecimal? = null,
    @Json(name = "totalMoney")
    val totalMoney: SquareMoney? = null,
    @Json(name = "totalTaxMoney")
    val totalTaxMoney: SquareMoney? = null,
    @Json(name = "totalDiscountMoney")
    val totalDiscountMoney: SquareMoney? = null,
    @Json(name = "totalTipMoney")
    val totalTipMoney: SquareMoney? = null,
    @Json(name = "totalServiceChargeMoney")
    val totalServiceChargeMoney: SquareMoney? = null
)

